[workspace]

members = [
    "examples/container/cpueater",
    "examples/container/crashing",
    "examples/container/datarw",
    "examples/container/hello",
    "examples/container/memeater",
    "examples/container/resource/ferris",
    "libcap-sys",
    "minijail/rust/minijail",
    "minijail/rust/minijail-sys",
    "north",
    "north_tests",
    "north_tests/test_container",
    "npk",
    "nstar",
    "sextant",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z' # Optimize for size
