[workspace]
members = [
    "examples/container/capabilities",
    "examples/container/cpueater",
    "examples/container/crashing",
    "examples/container/datarw",
    "examples/container/hello-world",
    "examples/container/memeater",
    "examples/container/resource/ferris",
    "examples/container/resource/hello-resource",
    "examples/container/seccomp",
    "libcap-sys",
    "minijail/rust/minijail",
    "minijail/rust/minijail-sys",
    "northstar",
    "northstar_tests",
    "northstar_tests/test_container",
    "npk",
    "nstar",
    "sextant",
    "stress",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
